### ISSUE TITLE
TypeError, number of arguments passed is too high

### ISSUE THREAD

**Issue by lapr0** [coagulant/critics#13]
Current configuration
OS: Ubuntu 16.04

When trying to run critics for testing or for live, this error occurs.
Not using partial() for setting itunes or google_play in cli() while providing a slack_webhook returns the same error, but reviews (if any) are sent to slack.

> Traceback (most recent call last):
>   File "/home/loic/github/crit/bin/critics", line 11, in <module>
>     sys.exit(main())
>   File "/home/loic/github/crit/lib/python3.5/site-packages/critics/__init__.py", line 9, in main
>     return cli(auto_envvar_prefix=envvar_prefix)
>   File "/home/loic/github/crit/lib/python3.5/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/loic/github/crit/lib/python3.5/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/loic/github/crit/lib/python3.5/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/loic/github/crit/lib/python3.5/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/loic/github/crit/lib/python3.5/site-packages/critics/commands.py", line 67, in cli
>     1000 * settings['beat'], loop)
> TypeError: __ init __() takes 3 positional arguments but 4 were given

**Comment by coagulant** [comment]
Please give clear steps to reproduce. Not sure what "Not using partial() for setting itunes or google_play in cli() while providing a slack_webhook" means

**Comment by lapr0** [comment]
In commands.py this variable:
`itunes = tornado.ioloop.PeriodicCallback(partial(app.poll_store, 'ios'),
                                                 1000 * settings['beat'], loop)`
If I run critics command, nothing will pop but the TypeError 4 args given, 3 wanted mentioned as title. But if I remove partial and modify the code to:
`itunes = tornado.ioloop.PeriodicCallback(app.poll_store('ios'), 1000 * settings['beat'], loop)`
and run `critics --ios=XXX --slack-webhook=MY_SLACK_WEBHOOK` I still get the same error, but reviews are posted to slack.
